# These are supported funding model platforms

github: # I don't have GitHub sponsors enabled.
patreon: # I don't have Patreon
open_collective: # what???
ko_fi: # I don't have Ko-fi
tidelift: # I don't know that
community_bridge: # I don't know that
liberapay: # I don't know that
issuehunt: # I don't know that
lfx_crowdfunding: # I don't know that
polar: # I don't have Polar
buy_me_a_coffee: # I don't have "Buy Me a Coffee"
thanks_dev: # I don't have thanks.dev
custom: # GG, NOW GITHUB AND I SPEAK THE SAME LANGUAGE, I mean, not English or Spanish, I mean I found what I wanted which was to put a custom... oh, you get it.
  - "https://penguinmod.com/"
  - "https://youtube.com/@danteelgameryt"
  - "https://danteelgamer-yt.itch.io/friday-night-funkin-optimized"
  - "https://streamlabs.com/danteelgamer_/merch"
